<a href="https://colab.research.google.com/github/Jaomiew/Multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Funcion**

```Python
def function_name(_Input_):
    do_something with _Input_ to produce _Output_
    return _Output_
```

## **funcion มีทั้งหมด 4 ส่วน**
1. บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def funcion_name():(ขาดไม่ได้)
2. กำหนดตัวแปรที่จะเป็น Input (ขาดไม่ได้)
3. ส่วนประมวลผล do_something with input to get Output (ขาดไม่ได้)
4. ส่วน Output return output (ขาดไม่ได้)
###เราใช้ เว้นวรรค (indent) เพื่อบอกขอบเขตของ code

## **สร้างฟังก์ชั่น**

In [4]:
def print_name(name,surname,ID):
    st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
    return st
print('outside function')

outside function


## **การเรียกใช้ฟังก์ชั่น**

In [5]:
print_name('วนิศรา','จงใจ','623021054-8')


'ชื่อ วนิศรา นามสกุล จงใจ ID 623021054-8'

In [6]:
output_string = print_name('วนิศรา','จงใจ','623021054-8')
print(output_string)

ชื่อ วนิศรา นามสกุล จงใจ ID 623021054-8


## **ฟังก์ชั่นไม่จำเป็นต้องมี output**

In [7]:
def print_name2(surname,ID,name):
    st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)

In [8]:
print_name2('วนิศรา', 'จงใจ', '623021054-8')

ชื่อ 623021054-8 นามสกุล วนิศรา รหัส จงใจ


In [9]:
op2 = print_name2('วนิศรา', 'จงใจ', '623021054-8')

ชื่อ 623021054-8 นามสกุล วนิศรา รหัส จงใจ


In [10]:
print(op2)

None


## **ฟังก์ชั่นไม่จำเป็นต้องมี input**

In [11]:
def pi():
    return 3.14159265359

In [12]:
#คำนวณพื้นที่วงกลมท่มีเส้นผ่านศูนย์กลางเท่ากับ 3
pi()*(1.5**2)

7.0685834705775

In [13]:
def print_my_name():
    print('วนิศรา จงใจ IDxxxxxxxxxxx')

In [14]:
print_my_name()

วนิศรา จงใจ IDxxxxxxxxxxx


### 1.  input ของfuncion ใน python มีสองเเบบ input ที่จำเป็นต้องใส่กับ input ที่ไม่จำเป็นต้องใส่ (มีค่า default) 
### 2. เราต้องเรียง intput ที่จำเป็นต้องใส่ขึ้นก่อน

In [15]:
def print_2lines_default(name, surname, ID, grade='F'):
    st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)
    st2=f'เกรดวิชา Multivariate >>> {grade}'
    print(st2)

In [16]:
print_2lines_default('วนิศรา','จงใจ','623021054-8')


ชื่อ วนิศรา นามสกุล จงใจ รหัส 623021054-8
เกรดวิชา Multivariate >>> F


In [17]:
print_2lines_default('วนิศรา','จงใจ','623021054-8','A')

ชื่อ วนิศรา นามสกุล จงใจ รหัส 623021054-8
เกรดวิชา Multivariate >>> A


### **เราสามารถเรียกฟังก์ชั่นโดยใช้ชื่อตัวแปรของฟังก์ชั่นช่วยได้**

In [18]:
print_name2(name='วนิศรา', surname='จงใจ', ID='623021054-8')

ชื่อ วนิศรา นามสกุล จงใจ รหัส 623021054-8


### **HW3 ให้เขียน function คำนวณจำนวนวินาทีจาก เวลาต่อไปนี้**

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

### **และ print ให้สวยงาม**

In [19]:
def print_time(time):
         time_sp = time.split('-') 
         Answer = int(time_sp[0])*60*60 + int(time_sp[1])*60 + int(time_sp[2])
         print(f'เวลา {time} คำนวณเป็นจำนวนวินาทีได้เท่ากับ {Answer} วินาที')

In [20]:
print_time('14-15-31')

เวลา 14-15-31 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 51331 วินาที


In [21]:
print_time('13-00-01')

เวลา 13-00-01 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 46801 วินาที


In [22]:
print_time('05-49-44')

เวลา 05-49-44 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 20984 วินาที


In [23]:
print_time('00-00-16')

เวลา 00-00-16 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 16 วินาที


# **Numpy -> pacage สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)**


Num + py -> Numercal + python

การใช้ Pakge
1. ```import``` ```ชื่อ Pakage```#เรียกใช้ Pakage
2. ชื่อ Pakage. =ชื่อฟังก์ชั่น #เรียกใช้ Functoin

In [27]:
import numpy

Data struture -> array

สร้าง array (numpy array)

In [33]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]]) # มีเเถว0กับเเถว1 

ชี้ค่าใน numpy array

In [39]:
mat_ex1[1] #[ใช้แถว,หลัก] เรียกใช้เเถว 1

array([9.1, 0.1, 0.3])

In [35]:
mat_ex1[1,1] #[ใช้แถว,หลัก] เรียกใช้เเถว 1 หลักที่ 1

0.1

ถ้าไม่มี numprarray

In [38]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [40]:
list_ex1[1][1] #ใส่เลขได้เเค่ตัวเดียว เรียกใช้เเถว 1 หลักที่ 1

0.1

In [41]:
list(list_ex1)
a = list_ex1[1]
print(a)
print(a[1])

[9.1, 0.1, 0.3]
0.1


Matrix Operation

Data 2 แบบ -> matrix (2D) , scalar (ตัวเลขค่าคงที่)

In [43]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


บวกกับลบ matrix เอาตัวเลขตำเเหน่งเดียวกันมาบวกกัน

In [44]:
mat_ex3 = mat_ex1 + mat_ex2
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


ข้อจำกัดคือ บวกกับลบต้องเหมือนกัน

mat_ex0

การตรวจสอบขนาดของ matrix

In [45]:
mat_ex3.shape

(2, 3)

In [47]:
mat_ex3.shape[0]

2

การคูณ matrix

In [51]:
print(mat_ex1)
print(mat_ex1.shape) #ขนาดของmatrix
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [48]:
mat_ex1 * mat_ex2 #ไม่ได้ทำแบบนี้

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

In [52]:
numpy.dot(mat_ex1,mat_ex2)

ValueError: ignored

สิ่งที่จะคูณmatrix ได้ (แถว*หลัก)

1. หลักของตัวข้างหน้า = แถวของ matrix ตัวข้างหลัง dot product (AAA,x , (x,ZZZ))= (AAA,ZZZ)

In [56]:
print(mat_ex1) 2*3 ตั้งทำให้เป็น 3*2
print(mat_ex1.shape) 2,3 
print(mat_ex2)       
print(mat_ex2.shape) 2,3 

SyntaxError: ignored

# Transpose กลับแถวเป็นหลัก กลับหลักเป็นเเถว

matrix.T

In [55]:
์๊numpy.dot(mat_1,mat_ex2.T) #(2,3).(3,2)

SyntaxError: ignored

In [57]:
numpy.dot(mat_1.T,mat_ex2) #(3,2).(2,3)

NameError: ignored